name: JhaliersToolpack
version: 1.0
main: org.jhalier.jhaliersToolpack.JhaliersToolpack
api-version: '1.21'
author: Jhalier | https://github.com/pwl-de

commands:
  dev:
    description: JhaliersToolpack Developer Commands
    usage: /dev <subcommand>
    aliases:
      - devhelp